# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origPanelId', models.IntegerField(blank=True)),
                ('origTitle', models.CharField(blank=True, max_length=64)),
                ('book', models.CharField(choices=[('Gene', 'Genesis'), ('Exod', 'Exodus'), ('Levi', 'Leviticus'), ('Nums', 'Numbers'), ('Deut', 'Deuteronomy')], max_length=4)),
                ('chapterStart', models.IntegerField()),
                ('verseStart', models.IntegerField()),
                ('chapterEnd', models.IntegerField()),
                ('verseEnd', models.IntegerField()),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=35)),
                ('firstName', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='StitchingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedDate', models.DateField(blank=True)),
                ('receivedDate', models.DateField(blank=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Panel')),
            ],
        ),
    ]
