# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_importdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participantType',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
