# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_participant_participanttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(upload_to='data/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='importdata',
            name='datafile',
        ),
        migrations.AddField(
            model_name='importdata',
            name='importDate',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 16, 20, 25, 14, 28582, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
